matrix:
  include:
    - os: linux

      dist: xenial

      language: cpp

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - make
            - g++-7
            - libgl1-mesa-dev

      install:
        - sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y
        - sudo apt-get update -q
        - sudo apt-get install qt511base qt511translations qt511tools qtchooser -y -q

      before_script:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1
        - source /opt/qt511/bin/qt511-env.sh
        - export VERSION=`git rev-parse --short HEAD`

      script:
        - mkdir build
        - cd build
        - qmake ../dispatcher.pro
        - make -j 2
        - ./tests/tests

      before_deploy:
        - cd ../
        - mkdir -p dispatcher.AppDir/usr/bin
        - cp build/dispatcher/dispatcher dispatcher.AppDir/usr/bin/dispatcher
        - cp icon/svg/dispatcher.svg dispatcher.AppDir/dispatcher.svg
        - curl -L https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage > linuxdeployqt
        - chmod a+x linuxdeployqt
        - ./linuxdeployqt dispatcher.AppDir/dispatcher.desktop -appimage

      deploy:
        provider: script
        skip_cleanup: true
        script: curl --upload-file dispatcher*.AppImage https://transfer.sh/dispatcher-git.$VERSION-x86_64.AppImage
        on:
          tags: false
          all_branches: true

    - os: linux

      dist: bionic

      language: ruby

      rvm: 2.6.3

      before_install:
        - gem update --system
        - gem install bundler:2.0.2

      install:
        - cd docs/user-manual
        - bundle install --jobs=3 --retry=3

      script:
        - bundle exec asciidoctor -o index.html index.adoc
        - bundle exec asciidoctor-pdf -o user-manual.pdf index.adoc

      before_deploy:
        - mkdir -p dist/user-manual
        - mv index.html dist/user-manual/index.html
        - mv user-manual.pdf dist/user-manual.pdf
        - cp -r images dist/user-manual/images

      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          local-dir: docs/user-manual/dist
          on:
            tags: false
            branch: master
