dist: xenial
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - make
      - g++-7

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y
  - sudo apt-get update -q
  - sudo apt-get install qt511base -y
  - mkdir -p ~/.config/qtchooser
  - echo -e "/opt/qt511/bin\n/opt/qt511/lib" > ~/.config/qtchooser/default.conf
  - qmake -v

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10

script:
  - mkdir build
  - cd build
  - qmake ../dispatcher.pro
  - make -j 2
  - ./tests/tests
