matrix:
  include:
    - os: osx

      osx_image: xcode10.3

      language: generic

      addons:
        homebrew:
          packages:
          - qt
          - make

      before_script:
        - export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
        - export PATH="/usr/local/opt/qt/bin:$PATH"

      script:
        - mkdir build
        - cd build
        - qmake ../dispatcher.pro
        - make -j 2
        - ./tests/tests

    - os: linux

      dist: bionic

      language: cpp

      addons:
        apt:
          packages:
            - make
            - libgl1-mesa-dev

      install:
        - sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-bionic -y
        - sudo apt-get update -q
        - sudo apt-get install qt511base qtchooser -y -q

      before_script:
        - mkdir -p ~/.config/qtchooser
        - echo -e "/opt/qt511/bin\n/opt/qt511/lib" > ~/.config/qtchooser/default.conf

      script:
        - mkdir build
        - cd build
        - qmake ../dispatcher.pro
        - make -j 2
        - ./tests/tests