matrix:
  include:
    - os: osx

      osx_image: xcode10.3

      language: generic

      addons:
        homebrew:
          packages:
          - qt
          - make

      before_script:
        - export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
        - export PATH="/usr/local/opt/qt/bin:$PATH"

      script:
        - mkdir build
        - cd build
        - qmake ../dispatcher.pro
        - make -j 2
        - ./tests/tests

    - os: linux

      dist: xenial

      language: cpp

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - make
            - g++-7
            - libgl1-mesa-dev

      install:
        - sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y
        - sudo apt-get update -q
        - sudo apt-get install qt511base qtchooser -y -q

      before_script:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1
        - source /opt/qt511/bin/qt511-env.sh

      script:
        - mkdir build
        - cd build
        - qmake ../dispatcher.pro
        - make -j 2
        - ./tests/tests

      before_deploy:
        - cd ../
        - mkdir -p dispatcher.AppDir/usr/bin
        - cp build/gui/dispatcher dispatcher.AppDir/usr/bin/dispatcher
        - cp icon/svg/dispatcher.svg dispatcher.AppDir/dispatcher.svg
        - curl -L https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage > linuxdeployqt
        - chmod a+x linuxdeployqt
        - export VERSION=`git rev-parse --short HEAD`
        - ./linuxdeployqt dispatcher.AppDir/dispatcher.desktop -appimage

      deploy:
        provider: script
        skip_cleanup: true
        script: curl --upload-file dispatcher*.AppImage https://transfer.sh/dispatcher-git.$VERSION-x86_64.AppImage
