image: Visual Studio 2015

platform: x64

install:
  - cinst make
  - cinst 7zip.install
  - cmd: echo "Extracting Qt for MinGW (static build)"
  - cmd: 7z x .\.deps\Qt-5.12.1-mingw-static.zip -y -otmp
  - cmd: move /Y .\tmp\5.12.1-mingw-static C:\Qt\5.12.1-mingw-static

build_script:
  - cmd: set PATH=C:\Qt\5.12.1-mingw-static\bin;C:\Qt\5.12.1\mingw73_64;%PATH%
  - cmd: set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
  - cmd: mkdir build
  - cmd: cd build
  - cmd: qmake ..\dispatcher.pro
  - cmd: make -j 2

artifacts:
  - path: build\gui\release\dispatcher.exe