version: "{build}"

image: Visual Studio 2017

platform: x64

before_build:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - set PATH=C:\Qt\5.12.3\msvc2017_64\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - qmake ..\dispatcher.pro
  - nmake

test_script:
  - tests\release\tests.exe

artifacts:
  - path: build\dispatcher\release\dispatcher.exe
    name: dispatcher-x64-windows.exe
